
name: Valheim CDK deployment

on: workflow_dispatch

permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    env:
      APPLICATION_PUBLIC_KEY: ${{ vars.APPLICATION_PUBLIC_KEY }}
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      ROUTE53_DOMAIN: ${{ vars.ROUTE53_DOMAIN }}
      ROUTE53_HOSTED_ZONE_ID: ${{ vars.ROUTE53_HOSTED_ZONE_ID }}
      SERVER_NAME: ${{ vars.SERVER_NAME }}
      SERVER_PASS: ${{ secrets.SERVER_PASS }}
      WORLD_NAME: ${{ vars.WORLD_NAME }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    # - name: Debug OIDC Claims
    #   uses: github/actions-oidc-debugger@main
    #   with:
    #     audience: sts.amazonaws.com

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        audience: sts.amazonaws.com
        role-to-assume: arn:aws:iam::399585304222:role/valheim-server-cdk-deploy
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}

    # - name: Test AWS Credentials
    #   run: |
    #     aws sts get-caller-identity
         
    - name: Install Lambda dependencies
      run: |
        pip install -r lambda/functions/requirements.txt -t layers/python
        
    - name: Zip Lambda dependencies
      run: |
        cd layers
        zip -r ../lambda-requirements.zip python
        cd ..
          
    - name: Install CDK tools
      run: |
        apt-get -qq update && apt-get -y install nodejs npm
        npm i -g cdk
        pip3 install -e cdk

    - name: Execute CDK
      run: |
        cd cdk
        cdk deploy --require-approval never
